# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

logSumExp_cpp <- function(x) {
    .Call(`_SpatMet_logSumExp_cpp`, x)
}

state_dist_cpp <- function(G12, G21) {
    .Call(`_SpatMet_state_dist_cpp`, G12, G21)
}

GeneralLoglikelihood_cpp <- function(y, r, s, u, Gamma, e_it, B, model, z_it, z_it2) {
    .Call(`_SpatMet_GeneralLoglikelihood_cpp`, y, r, s, u, Gamma, e_it, B, model, z_it, z_it2)
}

GeneralLoglikelihood_cpp2 <- function(y, r, s, u, Gamma, e_it, B, model, z_it, z_it2) {
    .Call(`_SpatMet_GeneralLoglikelihood_cpp2`, y, r, s, u, Gamma, e_it, B, model, z_it, z_it2)
}

