# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

logSumExp_cpp <- function(x) {
    .Call(`_SpatMet_logSumExp_cpp`, x)
}

logSumExp_cpp2 <- function(x) {
    .Call(`_SpatMet_logSumExp_cpp2`, x)
}

intPower <- function(a, b) {
    .Call(`_SpatMet_intPower`, a, b)
}

logVecMatMult <- function(logV, M) {
    .Call(`_SpatMet_logVecMatMult`, logV, M)
}

logVecMatMult2 <- function(logV, logM) {
    .Call(`_SpatMet_logVecMatMult2`, logV, logM)
}

JointTransitionMatrix_cpp <- function(gamma, K) {
    .Call(`_SpatMet_JointTransitionMatrix_cpp`, gamma, K)
}

state_dist_cpp2 <- function(Gamma) {
    .Call(`_SpatMet_state_dist_cpp2`, Gamma)
}

state_dist_cpp <- function(G12, G21) {
    .Call(`_SpatMet_state_dist_cpp`, G12, G21)
}

randomwalk2_cpp <- function(componentR, PrecisionR) {
    .Call(`_SpatMet_randomwalk2_cpp`, componentR, PrecisionR)
}

randomwalk2_cpp2 <- function(componentR, PrecisionR) {
    .Call(`_SpatMet_randomwalk2_cpp2`, componentR, PrecisionR)
}

dotproduct_cpp <- function(v1, v2) {
    .Call(`_SpatMet_dotproduct_cpp`, v1, v2)
}

dotproduct2_cpp <- function(z, v1) {
    .Call(`_SpatMet_dotproduct2_cpp`, z, v1)
}

quadform_cpp <- function(v1, z) {
    .Call(`_SpatMet_quadform_cpp`, v1, z)
}

seasonalComp2_cpp <- function(x, y, z) {
    .Call(`_SpatMet_seasonalComp2_cpp`, x, y, z)
}

seasonalComp2_cpp2 <- function(x, y, z) {
    .Call(`_SpatMet_seasonalComp2_cpp2`, x, y, z)
}

logIGMRF1_cpp <- function(x, y, z, rankdef) {
    .Call(`_SpatMet_logIGMRF1_cpp`, x, y, z, rankdef)
}

logIGMRF1_cpp2 <- function(x, y, z, rankdef) {
    .Call(`_SpatMet_logIGMRF1_cpp2`, x, y, z, rankdef)
}

GeneralLoglikelihood_cpp <- function(y, r, s, u, Gamma, e_it, B, model, z_it, z_it2) {
    .Call(`_SpatMet_GeneralLoglikelihood_cpp`, y, r, s, u, Gamma, e_it, B, model, z_it, z_it2)
}

GeneralLoglikelihood_cpp2 <- function(y, r, s, u, Gamma, e_it, B, model, z_it, z_it2) {
    .Call(`_SpatMet_GeneralLoglikelihood_cpp2`, y, r, s, u, Gamma, e_it, B, model, z_it, z_it2)
}

multGeneralLoglikelihood_cpp2 <- function(y, ndept, time, nstrain, a_k, r, s, u, Gamma, e_it, B, model, Bits, independentChains) {
    .Call(`_SpatMet_multGeneralLoglikelihood_cpp2`, y, ndept, time, nstrain, a_k, r, s, u, Gamma, e_it, B, model, Bits, independentChains)
}

hardconstraint_cpp <- function(x) {
    .Call(`_SpatMet_hardconstraint_cpp`, x)
}

rcpp_rmvn <- function(n, v, m) {
    .Call(`_SpatMet_rcpp_rmvn`, n, v, m)
}

rcpp_dmvn <- function(x, u, m) {
    .Call(`_SpatMet_rcpp_dmvn`, x, u, m)
}

rcpp_dmvn2 <- function(x, mu, sigma) {
    .Call(`_SpatMet_rcpp_dmvn2`, x, mu, sigma)
}

rcpp_updateCov <- function(C, x, n, xbar) {
    .Call(`_SpatMet_rcpp_updateCov`, C, x, n, xbar)
}

chol_cpp <- function(X) {
    .Call(`_SpatMet_chol_cpp`, X)
}

makematrix_cpp <- function(g12, g21) {
    .Call(`_SpatMet_makematrix_cpp`, g12, g21)
}

tcrossprod_cpp <- function(x) {
    .Call(`_SpatMet_tcrossprod_cpp`, x)
}

ColMeans_cpp <- function(M) {
    .Call(`_SpatMet_ColMeans_cpp`, M)
}

makeDiagMat_cpp <- function(epsilonS, n) {
    .Call(`_SpatMet_makeDiagMat_cpp`, epsilonS, n)
}

cov_cpp <- function(X) {
    .Call(`_SpatMet_cov_cpp`, X)
}

add2matrices_cpp <- function(A, B) {
    .Call(`_SpatMet_add2matrices_cpp`, A, B)
}

subtract2matrices_cpp <- function(A, B) {
    .Call(`_SpatMet_subtract2matrices_cpp`, A, B)
}

multiply2matrices_cpp <- function(A, B) {
    .Call(`_SpatMet_multiply2matrices_cpp`, A, B)
}

inv_cpp <- function(x) {
    .Call(`_SpatMet_inv_cpp`, x)
}

multInfer_cpp <- function(y, e_it, nstrain, Model, Bits, CrudeR, CrudeS, CrudeU, RW2PrecMat, RW1PrecMat, R, rankdef, independentChains, num_iteration, meanR, SumYk_vec) {
    .Call(`_SpatMet_multInfer_cpp`, y, e_it, nstrain, Model, Bits, CrudeR, CrudeS, CrudeU, RW2PrecMat, RW1PrecMat, R, rankdef, independentChains, num_iteration, meanR, SumYk_vec)
}

gradmultstrainLoglikelihood2_cpp <- function(y, e_it, nstrain, r, s, u, Gamma, B, Bits, a_k, Model, Q_r, Q_s, Q_u) {
    .Call(`_SpatMet_gradmultstrainLoglikelihood2_cpp`, y, e_it, nstrain, r, s, u, Gamma, B, Bits, a_k, Model, Q_r, Q_s, Q_u)
}

MMALA_cpp <- function(y, e_it, Model, Bits, CrudeR, CrudeS, CrudeU, RW2PrecMat, RW1PrecMat, Ru, rankdef, independentChains, num_iteration, meanR, step_sizes) {
    .Call(`_SpatMet_MMALA_cpp`, y, e_it, Model, Bits, CrudeR, CrudeS, CrudeU, RW2PrecMat, RW1PrecMat, Ru, rankdef, independentChains, num_iteration, meanR, step_sizes)
}

